### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: No serial data received.

### ISSUE THREAD

**Issue by razserv2010** [SasaKaranovic/DIY-Filament-Dryer#6]
I'm experiencing a error:
A fatal error occurred: Failed to connect to ESP32: No serial data received.
I connected using FTDI232
3V3 - 3V3
TX - RX
RX - TX
GND - GND

Could it be that the U3 component is MIC5365-1.8YD5-TR instead of 3V3?

![photo_2024-02-19_15-53-19](https://github.com/SasaKaranovic/DIY-Filament-Dryer/assets/47921926/d33bc3b1-97f0-464e-902b-9cee17ad9a02)
![photo_2024-02-19_15-53-24](https://github.com/SasaKaranovic/DIY-Filament-Dryer/assets/47921926/778eed46-7f0f-40de-a654-5330fe7dd32e)

**Comment by SasaKaranovic** [comment]
Hi Raz,

Sorry about that, there was a typo in the BoM but it's fixed now.
You would need `MIC5365-3.3YD5-TR` (or any other equivalent 3v3 LDO).

**Comment by razserv2010** [comment]
> Hi Raz,
> 
> Sorry about that, there was a typo in the BoM but it's fixed now.
> You would need `MIC5365-3.3YD5-TR` (or any other equivalent 3v3 LDO).

So this is the reason why the pc does not recognize the esp32?

**Comment by SasaKaranovic** [comment]
Yes. The regulator you are using is providing ESP32 with 1.8V which is not enough for it to power up.
If you switch to a 3.3V regulator, it should work (assuming everything else is ok).

**Comment by razserv2010** [comment]
> Yes. The regulator you are using is providing ESP32 with 1.8V which is not enough for it to power up.
> If you switch to a 3.3V regulator, it should work (assuming everything else is ok).

Thanks, I ordered 3v

**Comment by SasaKaranovic** [comment]
Sorry about that. The release files and the Altium files were updated a long time ago but when you mentioned it, I realized that the schematic is still calling out the wrong LDO.

**Comment by razserv2010** [comment]
> Sorry about that. The release files and the Altium files were updated a long time ago but when you mentioned it, I realized that the schematic is still calling out the wrong LDO.

Sorry but I didn't understand, LDO?

**Comment by SasaKaranovic** [comment]
[LDO regulator](https://en.wikipedia.org/wiki/Low-dropout_regulator).
The schematic had the wrong LDO part number. If you replace it with 3.3V regulator, it should work.

**Comment by razserv2010** [comment]
> [LDO regulator](https://en.wikipedia.org/wiki/Low-dropout_regulator).
> The schematic had the wrong LDO part number. If you replace it with 3.3V regulator, it should work.

Thanks, I ordered 3.3V

**Comment by razserv2010** [comment]
> [LDO regulator](https://en.wikipedia.org/wiki/Low-dropout_regulator). The schematic had the wrong LDO part number. If you replace it with 3.3V regulator, it should work.

I replaced the component but still:
A fatal error occurred: Failed to connect to ESP32: No serial data received.

What is the order of UART connections? , maybe I didn't connect correctly..

**Comment by razserv2010** [comment]
> [LDO regulator](https://en.wikipedia.org/wiki/Low-dropout_regulator).
> The schematic had the wrong LDO part number. If you replace it with 3.3V regulator, it should work.

 After I replaced the component, I was able to upload the firmware but the esp32 does not connect to wifi

**Comment by razserv2010** [comment]
Until the Si7021 sensors arrive, I want to connect the board but it won't let me connect to wifi
How can Si7021 be bypassed?

**Comment by katodo** [comment]
you can start to bypass "if (!temp_sensor_out.begin())" at the begin of code.

**Comment by SasaKaranovic** [comment]
@razserv2010 As @katodo said you could stub out (comment out) parts of the code that rely on Si7021.
But it might be tedious and also I would recommend using the sensor since some portions of the code depend on it.

I am working on new version of this board that should offer some improvements that people have asked for.

**Comment by razserv2010** [comment]
> @razserv2010 As @katodo said you could stub out (comment out) parts of the code that rely on Si7021.
> But it might be tedious and also I would recommend using the sensor since some portions of the code depend on it.
> 
> I am working on new version of this board that should offer some improvements that people have asked for.

The sensors arrived, trying to connect to wifi but without success, I opened a new issue about it.
