### ISSUE TITLE
(R4) component Also missing is the Bill of Materials

### ISSUE THREAD

**Issue by razserv2010** [SasaKaranovic/DIY-Filament-Dryer#8]
I noticed that the R4 component is missing, Could you please provide the name of the component needed?
![20240227_173306](https://github.com/SasaKaranovic/DIY-Filament-Dryer/assets/47921926/cef846a0-3a02-4020-844c-e0380f9ee79f)

**Comment by SasaKaranovic** [comment]
R4 is marked as DNP (do not populate or do not purchase). So you are correct not to populate it on the board.

This is a fallback if you are using an adjustable voltage regulator in which case you would change the value of R20 and R4.
