### ISSUE TITLE
ESP32 Can't connect to wifi

### ISSUE THREAD

**Issue by razserv2010** [SasaKaranovic/DIY-Filament-Dryer#9]
and continues trying Connecting to SSID

![צילום מסך 2024-02-29 161208](https://github.com/SasaKaranovic/DIY-Filament-Dryer/assets/47921926/f5c2827b-1b96-4565-8e57-03999407e740)

**Comment by SasaKaranovic** [comment]
Is your WiFi network by any chance 5GHz only?
ESP32 needs 2.4GHz WiFi network.

**Comment by razserv2010** [comment]
> Is your WiFi network by any chance 5GHz only? ESP32 needs 2.4GHz WiFi network.
Obviously, I'm trying to connect to wifi 2.4Ghz
Anyway, I found the user's fork: @benuron
And now the wifi connects and everything works fine.

**Comment by SasaKaranovic** [comment]
Thanks. I have updated the connect portion of the code.
